on: 
 workflow_dispatch: 
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04
    steps:
     - name: az login
       run: az login --service-principal -u 8cade307-832f-4fcd-a576-8a553f6edb82 -p "SXN8Q~7Zn9eV5GF9uNe1uy6YcWX5E~NNzJCxzazH" --tenant 8b0de87e-c47c-48cf-9e8e-1250310c221d
  
